EnzymeAD/Reactant.jl

src/Reactant.jl

code gets generated as `((Base.getfield(Base.getfield(args[3], layer_1), bias)).data = concrete_res_1)` instead of `((Base.getfield(Base.getfield(args[3], :layer_1), :bias)).data = concrete_res_1)`

Missing `Meta.quot`

---

src/Reactant.jl

Example usage:
```julia
julia> using Reactant
julia> W = Reactant.ConcreteRArray(randn(Float32, 10, 20))
x = Reactant.ConcreteRArray(randn(Float32, 20, 5))
Reactant.@code_hlo W * x
Module:
module attributes {transform.with_named_sequence} {
func.func @main(%arg0: tensor<20x10xf32>, %arg1: tensor<5x20xf32>) -> tensor<5x10xf32> {
%0 = stablehlo.dot_general %arg1, %arg0, contracting_dims = [1] x [0], precision = [DEFAULT, DEFAULT] : (tensor<5x20xf32>, tensor<20x10xf32>) -> tensor<5x10xf32>
return %0 : tensor<5x10xf32>
}
}
```
cc @mofeing

add `@code_hlo` macro to get mlir code

---

src/TracedRArray.jl

@wsmoses In Julia, a 0-dim array is not (programmatically) equal to a scalar, but we're treating as such in Reactant. We should be more careful about this, but meanwhile, I'm using this method implementation to keep compatibility between Reactant and non-Reactant code.

Implement `only` for `TracedRArray`

---

src/TracedRArray.jl
src/Tracing.jl
src/utils.jl

Depends on #68 
~~DON'T MERGE BEFORE IT~~
It basically ads some `@nospecialize` annotations to some methods to lower the amount of codegen.
Also, it fixes a small performance bug (I wasn't reusing the `ReactantInterpreter`, so we weren't reusing the cache).

Despecialize some methods to lower excessive codegen

---

deps/build_local.jl

fixes on machines without `nvidia-smi`. Also add an option to pass in `dbg` or `opt`

fix: local JLL build script

---

src/Interpreter.jl

This fixes `set!` on types with customized `traced_getfield`

Replace `getfield` for `traced_getfield` in `set!`

---

deps/ReactantExtra/API.cpp
deps/ReactantExtra/BUILD

Used to explore the damn bug of not honoring Apple's aarch64 call convention.

Export `GetDefaultTargetTriple` symbol

---

src/TracedRArray.jl

Fixes one of the errors in #148

Bypass identical construction on `TracedRArray`

---

src/TracedRArray.jl
src/Tracing.jl
test/basic.jl

It's not yet finished, but this should fix #148

Generalize `Base._cat` to non-`Val`, typed `Base._cat_t` and implement `typed_hcat`, `typed_vcat`, `typed_hvcat`, `typed_hvncat`

---

.github/workflows/regenerate-dialects.yml
deps/ReactantExtra/BUILD
deps/ReactantExtra/make-dialects.jl
docs/make.jl
src/mlir/Dialects.jl
src/mlir/Dialects/Affine.jl
src/mlir/Dialects/Arith.jl
src/mlir/Dialects/Builtin.jl
src/mlir/Dialects/CHLO.jl
src/mlir/Dialects/Enzyme.jl
src/mlir/Dialects/Func.jl
src/mlir/Dialects/StableHLO.jl
src/mlir/Dialects/VHLO.jl

This PR moves the Julia bindings to the MLIR dialects out of the JLL and moves the regeneration process to this repo. It should fix the "URL to non-existent file" bug in the docs.
In order to not make this tedious, the PR includes a workflow to run the regeneration every day and open a PR if it found any change.

Move Julia bindings to MLIR dialects out of JLL

---

.github/workflows/regenerate-mlir-bindings.yml

Refactor regenerate-mlir-bindings.yml workflow

---

deps/ReactantExtra/make-bindings.jl
src/Compiler.jl
src/ConcreteRArray.jl
src/Reactant.jl
src/Tracing.jl
test/basic.jl
test/compile.jl

realized I need this to correctly compile conditionals with scalars assignments in the branches
```julia
using Reactant
x = (3, [3.14])
function f(x)
return x[1] * x[2]
end
x_ra = Reactant.to_rarray(x; track_numbers=(Number,))
f2 = @compile f(x_ra)
f2(Reactant.to_rarray((5, [3.14]); track_numbers=(Number,)))
x_ra2 = Reactant.to_rarray(x)
f3 = @compile f(x_ra2)
f3(Reactant.to_rarray((5, [3.14])))
```

feat: support tracing scalars

---

deps/ReactantExtra/API.cpp
deps/ReactantExtra/BUILD
src/mlir/IR/Attribute.jl
src/mlir/MLIR.jl

In one of our applications, we're running into this error:
```julia
MethodError: Cannot `convert` an object of type ComplexF64 to an object of type Reactant.MLIR.API.MlirAttribute
Closest candidates are:
convert(::Type{T}, !Matched::T) where T
@ Base Base.jl:84
convert(::Type{T}, !Matched::ConcreteRArray{T, 0}) where T
@ Reactant ~/.julia/packages/Reactant/dFd6D/src/ConcreteRArray.jl:73
convert(::Type{Reactant.MLIR.API.MlirAttribute}, !Matched::Reactant.MLIR.IR.Attribute)
@ Reactant ~/.julia/packages/Reactant/dFd6D/src/mlir/IR/Attribute.jl:12
...
Stacktrace:
[1] Reactant.MLIR.IR.Attribute(attribute::ComplexF64)
@ Reactant.MLIR.IR ~/.julia/packages/Reactant/dFd6D/src/mlir/IR/Attribute.jl:2
[2] autodiff(::ReverseMode{true, false, FFIABI, false, true}, …
```

Add C-API for constructing Complex Attributes

---

src/Tracing.jl
test/tracing.jl

fixes #138 
mostly updates https://github.com/EnzymeAD/Reactant.jl/pull/140

feat: specialize dispatches for faster concrete array generation

---

src/Compiler.jl
src/mlir/IR/Context.jl
test/bcast.jl
test/compile.jl

Disables multithreaded MLIR contexts as suggested in https://github.com/jax-ml/jax/issues/16272
the test needs to run `@compile` at least a number somewhat above 8000 times in macOS (I put 10,000), so it increases core test time from 2 minutes to... 7 minutes 😅

fix resource exhaustion bug #190

---

deps/ReactantExtra/API.cpp

Looks like `MLIR_CAPI_EXPORTED` does nothing in here so it doesn't use the C ABI, and due to name demangling, it doesn't get exported.
CC @Todorbsc

Replace `MLIR_CAPI_EXPORTED` for `extern "C"`

---

.github/workflows/CI.yml
Project.toml
ext/ReactantAbstractFFTsExt.jl
ext/ReactantNNlibExt.jl
test/Project.toml
test/integration/fft.jl
test/nn/nnlib.jl
test/runtests.jl

feat: functionalities for supporting NeuralOperators.jl

---

src/TracedRArray.jl
src/TracedRNumber.jl
src/mlir/IR/Attribute.jl
test/complex.jl
test/nn/nnlib.jl

fix: bypass segfault with fill complex

---

src/TracedRArray.jl
src/TracedRNumber.jl
test/basic.jl
test/nn/nnlib.jl

feat: add support for `clamp` and `clamp!`

---

src/Compiler.jl
src/mlir/IR/IR.jl
src/mlir/IR/Pass.jl

This is similar to the Enzyme-JAX lit tests where the verifier is disabled between passes for some complex-related test cases.

Disable verifier in main pass manager pipeline

---

src/Compiler.jl
test/compile.jl

Use gensym-ed variable in `@compile` and `@jit`

---

src/mlir/IR/AffineMap.jl
src/mlir/IR/Attribute.jl
src/mlir/IR/IntegerSet.jl
src/mlir/IR/Location.jl
src/mlir/IR/Type.jl
test/compile.jl

the pointer should actually be `int *`, not `uint8_t *`. Also calling `pointer` explicitly is unsafe and unnecessary. 
Closes #277.
This was also probably the cause for #115

fix attribute for arrray of bools

---

src/mlir/IR/Module.jl
test/compile.jl

Messes exporting stablehlo see https://github.com/LuxDL/Lux.jl/pull/1088/files#r1845238905

fix: don't print "Module"

---

src/Compiler.jl

I missed the `@code_hlo` in my previous pr (#274).
I've now deduplicated the code for `@compile`, `@jit`, and `@code_hlo`.
Option kwargs passed to `@code_hlo` where handled slightly differently compared to the other two macros, now they're handled the same but maybe someone should check whether `@code_hlo` kwarg handling does what it's supposed to do.

gensym in `@code_hlo`

---

src/Tracing.jl
test/tracing.jl

Test to check that:
1. `traced_type` for `ArrayToConcrete` fails if there are array-typed fields whos type isn't captured by the type parameter list
2. The error isn't a stackoverflow because recursion is properly handled.

test for traced_type where array isn't captured by type param

---

src/mlir/IR/Operation.jl

`Operation` can't be constructed with null, but since it is mutable, the operation field can be ([and is](https://github.com/EnzymeAD/Reactant.jl/blob/6f7b25f49fb92f014ada6eba1ec6d25603fa59c0/src/Compiler.jl#L359C1-L359C51)) sometimes replaced with `C_NULL`.
I ran into this when running through the code using a debugger. Past the point where the operation contains null, the program segfaults because the debugging interface tries to show all live variables.

add check for null in `show(::Operation)`. 

---

ext/ReactantArrayInterfaceExt.jl
src/Compiler.jl
src/Tracing.jl
test/Project.toml
test/basic.jl

Allows for a hook to ensure that we never end up propagating Array of Traced Values.
Related example for Tracker.jl where propagating Array{<:TrackedReal} leads to terrible performance https://github.com/LuxDL/Lux.jl/blob/cb0900f5350541a45e01af9ef12cc3d3e8df65d3/lib/LuxCore/ext/LuxCoreArrayInterfaceTrackerExt.jl#L8-L16

feat: define aos_to_soa

---

Project.toml

Makes sure that we auto-use the subdirectory package during development. Has no effect when the Project is not directly loaded (and no end user is affected)

chore: specify sources for local dev

---

src/Compiler.jl
test/compile.jl

there's a problem when returning a compiled function returns an `Array` in which the values are vectorized
```julia
julia> x = [1 2; 3 4; 5 6]
3×2 Matrix{Int64}:
1  2
3  4
5  6
julia> x2 = Reactant.to_rarray(x)
3×2 ConcreteRArray{Int64, 2}:
1  2
3  4
5  6
julia> g = Reactant.compile((x2,)) do _
x
end
Reactant.Compiler.Thunk{Symbol("###5_reactant#61915")}()
julia> g(x2)
6-element Vector{Int64}:
1
3
5
2
4
6
```
this PR solves it by adding a `reshape` in the `Expr` returned by `create_result(::Array)`, but the optimal implementation would be to use array literals (which i don't know how to write using `Expr`)
CC @Todorbsc

fix `create_result(::Array)` for non-vectors

---

src/ConcreteRArray.jl
src/Reactant.jl
src/TracedRArray.jl
src/TracedRNumber.jl
test/basic.jl

we had an issue in which some inner function was calling `collect` on a `TracedRArray`, which would error.
this PR implements `collect(::TracedRArray)` as just a copy of the `TracedRArray`

implement `collect` for `TracedRArray`

---

Project.toml
ext/ReactantYaoBlocksExt.jl

we run into some problems when trying to use a quantum circuit from Yao but whose parameters are traced by Reactant. specially, the LuxurySparse (which Yao uses a lot) arrays are quite problematic when used 
in the future, it might be better to use MLIR's sparse tensor types, but for now this is more than ok.
@wsmoses i know we discussed about creating this package extension here or in YaoBlocks.jl, but right now i'm on a rush and this is faster to get merged. also, in the future some changes in Reactant might fix the problems we had with the sparse arrays and thus, it might make sense to have it here for fast iteration. i'm pro moving it to YaoBlocks (if @Rogger-Luo is ok with it) once Reactant stabilizes.
CC @Todorbsc

fix `YaoBlocks.mat` for rotation gates with `TracedRNumber` parameters

---

src/Ops.jl
src/mlir/IR/Location.jl
src/utils.jl

@wsmoses i made the debug info optional because calling `stacktrace` has a big overhead. for example, `stacktrace` takes around 800-900 $\mu s$ in my laptop, while creating a `Location` takes around 3 $n s$
in order to add the debug info, i've added the `DEBUG_MODE` global var and the `with_debug` method to manage it

add optional debug info to Ops calls

---

src/ConcreteRArray.jl

```julia
julia> (ConcreteRArray(rand(100)),) # BEFORE
(ConcreteRArray{Float64, 1}([0.2535878726439841, 0.30146547100371024, 0.10047529184554504, 0.14394571836180303, 0.7447120689993926, 0.052444279563234164, 0.5068276912166574, 0.8361486344452231, 0.3206392318691902, 0.8738208419377047, 0.829888160187986, 0.05448133909341113, 0.7150961022795176, 0.8815815979446093, 0.4021192558958505, 0.6242368917575722, 0.31725390184551217, 0.43709239292231505, 0.7729125669613391, 0.12977819409489444, 0.7637736543714921, 0.3491923403480377, 0.935230455126192, 0.23266180405040526, 0.6383365404589012, 0.9025904181965533, 0.8012484503917107, 0.9301741523727763, 0.02594794780136722, 0.4410470553806616, 0.3048766390000852, 0.3083245690448847, 0.9388067728964168, 0.492918692961102, 0.4820793663137074, …
```

fix: preserve IOContext for printing

---

ext/ReactantYaoBlocksExt.jl

```julia
using Reactant
using YaoBlocks
θ = ConcreteRNumber(rand())
f(x) = mat(ComplexF64, Rz(x))
@code_hlo optimize = false f(θ)
```

reduce codegen on `YaoBlocks.mat` methods

---

ext/ReactantArrayInterfaceExt.jl
ext/ReactantNNlibExt.jl
src/ConcreteRArray.jl
src/Ops.jl
src/Reactant.jl
src/TracedRArray.jl
src/TracedRNumber.jl
src/linear_algebra.jl
test/integration/linear_algebra.jl
test/nn/nnlib.jl
test/ops.jl
test/wrapped_arrays.jl

fixes #339 
The main trick here is to preserve `ReshapedArray` type. Applies the fix for the following types for the time being:
1. ReshapedArray
2. Adjoint
3. Transpose
4. Diagonal
5. PermutedDimsArray
Adds the following LinearAlgebra functionality
1. `diag`
2. `diagm`
Updated NNlibExt to handle wrappers correctly

feat: correct handling of wrapped arrays functionalities

---

src/TracedRArray.jl
test/basic.jl

Closes #360 
This PR leverages `broadcast_to_size` to define outer repeating (the default for `Base.repeat`) of traced arrays.
I'm new here, so I may have missed something, but this looks promising:
```julia
julia> @code_hlo repeat(rand(2,3) |> Reactant.to_rarray, 5, 7, 11)
module {
func.func @main(%arg0: tensor<3x2xf64>) -> tensor<11x21x10xf64> {
%0 = stablehlo.reshape %arg0 : (tensor<3x2xf64>) -> tensor<1x1x1x3x1x2xf64>
%1 = stablehlo.transpose %0, dims = [5, 4, 3, 2, 1, 0] : (tensor<1x1x1x3x1x2xf64>) -> tensor<2x1x3x1x1x1xf64>
%2 = stablehlo.broadcast_in_dim %1, dims = [0, 1, 2, 3, 4, 5] : (tensor<2x1x3x1x1x1xf64>) -> tensor<2x5x3x7x1x11xf64>
%3 = stablehlo.transpose %2, dims = [5, 4, 3, 2, 1, 0] : (tensor<2x5x3x7x1x11xf64>) -> tensor<11x1x7x3x5x2xf64>
%4 = stablehlo.reshape %3 : …
```

Define outer `repeat` method for `TracedRArray`

---

.buildkite/pipeline.yml
.github/workflows/CI.yml

Run CI on aarch64

---

src/Ops.jl

fix `backtrace` calls on debug mode

---

deps/ReactantExtra/BUILD
deps/ReactantExtra/make-bindings.jl

@wsmoses i'm getting this error
```
external/enzyme_ad/src/enzyme_ad/jax/Dialect/EnzymeXLAOps.td:12:9: error: could not find include file 'Enzyme/MLIR/Dialect/Dialect.td'
include "Enzyme/MLIR/Dialect/Dialect.td"
^
external/enzyme_ad/src/enzyme_ad/jax/Dialect/EnzymeXLAOps.td:12:9: error: Unexpected token at top level
include "Enzyme/MLIR/Dialect/Dialect.td"
```

generate EnzymeXLA dialect bindings

---

src/utils.jl

~~This doesn't work yet! It only caches the top level codeinfo, some other absint method needs to be overwritten to do it properly.
Only tested on Julia 1.11~~
CI passes, and it seems like the cicache is being filled, I don't have a good test to show improvements though.
```julia
f(a, b) = a .* b
a = rand(10)
b = rand(10)
a_ra = Reactant.to_rarray(a)
b_ra = Reactant.to_rarray(b)
g(a, b) = @noinline f(a, b)
@code_hlo(g(a, b))
result = CC.get(CC.code_cache(Reactant.ReactantInterpreter()), Base.method_instance(f, Tuple{Vector{Float64}, Vector{Float64}}), nothing)
```

Inference cache

---

ext/ReactantNNlibExt.jl
src/TracedRArray.jl
src/TracedRNumber.jl
test/basic.jl

feat: indexing using traced values

---

ext/ReactantCUDAExt.jl
src/Tracing.jl
test/integration/cuda.jl

Can't test end-to-end but the HLO contains the stores.
```julia
using Reactant, CUDA
A = ConcreteRArray(fill(1))
struct MyStruct{T, B}
b::B
A::T
end
function f!(tup)
tup[1].A[] = 2
return nothing
end
s = MyStruct(10, A)
f(s) = @cuda threads=1 f!((s, s))
@code_hlo optimize=false f(s);
```

linearize aliased kernel args

---

src/Reactant.jl
src/stdlibs/Base.jl
test/basic.jl

Concatenating a number with an RArray does not result in an RArray.
This PR addresses this issue, based on https://github.com/JuliaGPU/GPUArrays.jl/pull/379/files.
The GPU backend encounters a scalar index error when the `@allowscalar` is not used, while the CPU backend functions correctly without it.
(Fixes https://github.com/EnzymeAD/Reactant.jl/issues/511)

Make v and hcat with numbers work.

---

src/ConcreteRArray.jl
src/Ops.jl
src/TracedRArray.jl
src/TracedRNumber.jl
test/ops.jl
test/runtests.jl
test/sorting.jl

feat: sorting and related functions

---

Project.toml
ext/ReactantCUDAExt.jl
ext/ReactantOffsetArraysExt.jl
src/Reactant.jl
src/TracedUtils.jl
src/Tracing.jl
test/basic.jl
test/compile.jl
test/control_flow.jl
test/struct.jl
test/tracing.jl

Trying to speed up compile time

Despecialize make_tracer

---

.github/workflows/CI.yml
docs/Project.toml
docs/make.jl

Use `[sources]` section of `docs/Project.toml` instead of messing with `LOAD_PATH`.  Same as https://github.com/EnzymeAD/Enzyme.jl/pull/2265.

Simplify process to builds docs

---

.github/workflows/benchmark_aggregate.yml
.github/workflows/regenerate-mlir-bindings.yml

While we evaluate a move to Runic, this should resolve the problem that the formatting job and bindings generation job conflict with each other due to an [upstream bug in JuliaFormatter](https://github.com/domluna/JuliaFormatter.jl/issues/897).

[CI] Format generated files twice to work around JuliaFormatter bug

---

.github/workflows/CI.yml
.github/workflows/Documenter.yaml
.github/workflows/benchmark_aggregate.yml
.github/workflows/downgrade.yml
.github/workflows/format-check.yml

Restrict running different workflows based on the touched files.  This should _slightly_ reduce CI workload.

[GHA] Add `paths` settings for workflow triggers

---

lib/ReactantCore/src/ReactantCore.jl
src/ControlFlow.jl
test/control_flow.jl

respect scopping rules in for

---

.buildkite/pipeline.yml
.github/workflows/CI.yml
test/integration/cuda.jl
test/runtests.jl

Let's see how this fares.  The idea is to reduce a little bit pressure on the `juliaecosystem` runners.

[CI] Move tests on aarch64 linux to GitHub Actions

---

src/Ops.jl
src/TracedRArray.jl
src/TracedUtils.jl
test/wrapped_arrays.jl

fixes #599 (I will add a test)

feat: support dynamic indexing for reshaped arrays

---

src/TracedRArray.jl
src/TracedUtils.jl
src/stdlibs/LinearAlgebra.jl
test/basic.jl
test/indexing.jl
test/integration/linear_algebra.jl
test/runtests.jl
test/wrapped_arrays.jl

I also moved the indexing tests into a single file to avoid polluting "basic" more

feat: more indexing support

---

test/integration/cuda.jl

[tests] Always skip CUDA tests on non-CUDA machines

---

src/Interpreter.jl
test/autodiff.jl

Fixes #593
(I still have a problem with rev-rule that i wasn't having before but that's probably on my side)

Fix dense elements attribute in `Enzyme.autodiff` #593

---

src/Ops.jl
src/TracedRArray.jl
test/indexing.jl

feat: support more set indexing

---

deps/ReactantExtra/.bazelrc
deps/ReactantExtra/API.cpp
deps/ReactantExtra/WORKSPACE

With previous commit I was running into [fun compilation errors on macOS](https://github.com/JuliaPackaging/Yggdrasil/pull/10313#issuecomment-2616420694).

[ReactantExtra] Bump XLA version

---

src/Devices.jl

There's no `trim` function in Julia `Base`.

Replace `trim` -> `strip`

---

src/TracedRArray.jl
test/indexing.jl

In the case in which one wants to set inplace a vector (so its dimension is `(N,)`) into some target traced vector with the colon-index operator, there is an ambigüity between two function signatures:
```julia
Base.setindex!(a::TracedRArray{T,N}, v, ::Colon) where {T,N}
```
and
```julia
const N = 1
Base.setindex!(a::TracedRArray{T,N}, v, indices::Vararg{Any,N}) where {T,N}
```
```julia
using Reactant
function ipop!(y, x)
y[:] = x
end
x = Reactant.to_array([1.0, 2.0])
y = similar(x)
@jit ipop!(y, x)
```
> `ERROR: MethodError: setindex!(::Reactant.TracedRArray{Float64, 1}, ::Reactant.TracedRArray{Float64, 1}, ::Colon) is ambiguous.`
> 
> `Candidates:`
> `  setindex!(a::Reactant.TracedRArray{T, N}, v, ::Colon) where {T, N}`
> `    @ Reactant.TracedRArrayOverrides …

Feature: allow colon indexing of traced **vectors**

---

deps/ReactantExtra/src/ifrt/LoadedExecutable.cpp
deps/ReactantExtra/src/memory_management.cpp
deps/ReactantExtra/src/memory_management.hpp

This is not a fully engineered fix (many design solutions to consider for extensibility), but for now, I've put together this quickfix for the compile errors.

[IFRT] Compile error hotfix

---

ext/ReactantCUDAExt.jl
test/integration/cuda.jl

Implementing suggestion at https://github.com/EnzymeAD/Reactant.jl/pull/674#issuecomment-2629092644
Close #674.

[ReactantCUDAExt] Skip precompile load on Julia v1.11.3

---

deps/ReactantExtra/API.cpp

Not tested yet, but based on https://github.com/EnzymeAD/Reactant.jl/issues/663#issuecomment-2629665961 it should work.  Will require a change in the compiler on the Julia side in a follow up PR.

[ReactantExtra] Add argument to `ClientCompile` to pass CUDA data dir

---

src/Ops.jl
src/TracedRArray.jl
src/TracedRNumber.jl
src/stdlibs/LinearAlgebra.jl

(Instead of creating a dummy traced array containing no mlir_data)
https://github.com/EnzymeAD/Reactant.jl/pull/523#issuecomment-2606965530

make `similar` return empty tensors.

---

src/Tracing.jl
test/tracing.jl

Resolves https://github.com/EnzymeAD/Reactant.jl/issues/696

Ref ptr fix

---

deps/ReactantExtra/WORKSPACE

We used to do that because in older macOS SDKs this variable was not available, but with https://github.com/JuliaPackaging/Yggdrasil/pull/10473 we switched to a newer SDK (11.3) and this hack isn't necessary anymore.
I verified locally that I could build successfully for both x86_64-darwin and aarch64-darwin in BinaryBuilder.  Opening as draft waiting for https://github.com/JuliaPackaging/Yggdrasil/pull/10473 to be merged.

[ReactantExtra] Stop removing references to `hardware_interference_size`

---

ext/ReactantCUDAExt.jl
test/basic.jl

@gbaraldi vendoring this in interim to unblock kernels

vendor optimize

---

src/Tracing.jl
test/tracing.jl

fix: don't trace val

---

.github/workflows/CI.yml

* Run tests on ubuntu-22.04-arm instead of ubuntu-24.04-arm: the former is considered more stable than the latter and doesn't randomly fail on the `actions/checkout` workflow.
* Manually install packages only in Julia v1.10, to avoid unnecessary double steps.

[GHA] Some improvement to CI setup

---

src/TracedRNumber.jl
test/basic.jl

This should help with https://github.com/CliMA/Oceananigans.jl/pull/4096#issuecomment-2661293409.  ~Opening as a draft until I figure out where to test these new methods.~ ***Edit***: tests added.

Support tracing of `rem` with only one operand being a `ConcreteRNumber`

---

.github/workflows/CI.yml
.github/workflows/downgrade.yml

`macOS-13` is native x86_64 hardware and avoids running through Rosetta, which can lead to nasty test failures. Similar in spirit to https://github.com/EnzymeAD/Enzyme.jl/pull/2273.
Based on a [quick test](https://github.com/EnzymeAD/Reactant.jl/actions/runs/13373752002/job/37348145953), this should fix #763, we'll see what a full run says.

[GHA] Run x86_64 macOS jobs on macOS-13 runners

---

src/Types.jl

to make sure oceananigans precompiles as it uses the var [we can amend the defn later]

restore anyconcreterarray

---

ext/ReactantCUDAExt.jl
src/Compiler.jl
src/Ops.jl
src/Sharding.jl
src/TracedUtils.jl

- `Mesh` no longer stores ntuples. It would be extremely suboptimal when scaling across 100s of nodes.
- Logical Device IDs are always ordered hence we store it as a `Base.OneTo(N)`

fix: simplify Mesh implementation

---

src/stdlibs/LinearAlgebra.jl
test/integration/linear_algebra.jl

I follow the standard lib LinearAlgebra.jl that it always casts ```a``` and ```b``` to the ```eltype``` of ```X``` and ```Y```.  If ```a``` is ```float``` and ```X``` has ```eltype Int``` , it will throw an error.

adding axpy! and axpby! to linear algebra

---

deps/ReactantExtra/API.cpp
deps/ReactantExtra/WORKSPACE

This PR fixes the registration of the LLVM dialect, and adds a lil extra utility for parsing single MLIR ops. The only limitation is that since we don't know the SSA names in advance, it fails when we need pass a argument, but it's still useful for writing some simple `func.func`s that need to be injected in the module.

ReactantExtra changes to fix MPI PR

---

.github/workflows/CI.yml

macOS runners are occasionally hanging, having a shorter timeout helps by making the job fail earlier than waiting uselessly for 90 minutes, saving some time, especially important since there are only 5 concurrent macOS runners across the entire organisation.

[CI] Set timeout of run-tests job to 60 minutes

---

src/Ops.jl
test/ops.jl

I deliberately did not test on non-commutative operators—it will fail when tested against Julia's reduce. I read the discussion on the internet that it is supposed to be so, i.e., reduce should take a commutative operator; otherwise, the result will be non-deterministic, especially in a parallel system.

adding reduce to Ops.jl

---

.github/workflows/CI.yml

Ref: https://github.com/EnzymeAD/Reactant.jl/issues/867.
I'm not particularly happy about this, but short of having someone to fix the issue above in this way we can have green CI back.

[CI] Disable failing macOS-13 jobs

---

.github/workflows/CI.yml

I was under the impression the neural networks jobs were safe from #867, but it looks like I was wrong, so with this PR we just disable all macOS-13 jobs entirely.

[CI] Disable `macOS-13` entirely, not just `core` and `integration`

---

src/ConcreteRArray.jl
src/TracedRArray.jl
test/indexing.jl

ref: https://github.com/EnzymeAD/Reactant.jl/pull/876#pullrequestreview-2674489437
ref: https://github.com/PRONTOLab/GB-25/issues/32

`mapreducedim!` for concreterarrays

---

deps/ReactantExtra/API.cpp

This fixes a problem in the previous implementation that was preventing us from injecting the MLIR code string inplace on an already existing MLIR block (verifier was the issue).

[ReactantExtra] Fix `mlirOperationParse` and add `mlirOperationInject`

---

src/ConcreteRArray.jl
src/Ops.jl
src/TracedRArray.jl
test/basic.jl

stablehlo.reduce has somewhat different semantics compared to julia's reduce. Applying the init values later ensures that the results are consistent

fix: apply init values after reduction

---

src/ConcreteRArray.jl
src/Ops.jl
src/TracedRArray.jl
test/basic.jl

https://github.com/EnzymeAD/Reactant.jl/pull/882/ but without https://github.com/EnzymeAD/Reactant.jl/pull/881

fix: `map!` and `map`

---

docs/make.jl
docs/src/.vitepress/config.mts
docs/src/api/sharding.md
docs/src/tutorials/index.md
docs/src/tutorials/multihost.md
src/Distributed.jl
src/xla/Distributed.jl
src/xla/IFRT/Array.jl
test/cluster_detector.jl
test/runtests.jl
test/sharding.jl

Last bit needed to run on ALPs. By default we run a single GPU per process, but if `single_gpu_per_process` is set to false, we will use all GPUs accessible locally in that process

feat: slurm detector + multigpu single process

---

src/Ops.jl
src/TracedRArray.jl
test/basic.jl

the breakage in GB was likely from https://github.com/EnzymeAD/Reactant.jl/pull/892. Testing in https://github.com/PRONTOLab/GB-25/pull/50

fix: apply init values after reduce

---

src/Compiler.jl
test/buffer_donation.jl

```mlir
module @reactant_fn attributes {mhlo.num_partitions = 8 : i64, mhlo.num_replicas = 1 : i64} {
sdy.mesh @mesh = <["x"=2, "y"=2, "z"=2]>
func.func @main(%arg0: tensor<2x2x2xf64> {reactant.donated, sdy.sharding = #sdy.sharding<@mesh, [{"z"}, {"y"}, {"x"}]>}) -> (tensor<2x2x2xf64> {sdy.sharding = #sdy.sharding<@mesh, [{"z"}, {"y"}, {"x"}]>}) {
%cst = stablehlo.constant dense<[[[0.63084595408749855, 0.94852621203725684], [0.37331956478281025, 0.55284767325502948]], [[0.62904737184899251, 0.71429285082865546], [0.51198077904593264, 0.26607778955478978]]]> : tensor<2x2x2xf64>
return %cst : tensor<2x2x2xf64>
}
}
```

feat: add a reactant.donated attr to donated args

---

src/TracedUtils.jl

Reverts EnzymeAD/Reactant.jl#953
This causes
```
TypeError: in new, expected Reactant.TracedRArray{Float32, 2}, got a value of type Reactant.TracedRNumber{Float32}
Stacktrace:
[1] make_tracer(seen::Reactant.OrderedIdDict{Any, Any}, prev::Any, path::Any, mode::Reactant.TraceMode; track_numbers::Type, sharding::Any, runtime::Any, kwargs::@Kwargs{toscalar::Bool})
@ Reactant ~/work/Reactant.jl/Reactant.jl/src/Tracing.jl:1117
[2] make_tracer(seen::Reactant.OrderedIdDict{Any, Any}, prev::Any, path::Any, mode::Reactant.TraceMode; track_numbers::Type, sharding::Any, runtime::Any, kwargs::@Kwargs{toscalar::Bool})
@ Reactant ~/work/Reactant.jl/Reactant.jl/src/Tracing.jl:1091
[3] make_tracer
@ ~/work/Reactant.jl/Reactant.jl/src/Tracing.jl:1010 [inlined]
[4] make_mlir_fn(f::typeof(+), …
```

Revert "fix: noop check"

---

src/Ops.jl
src/TracedRArray.jl

Essentially ensures that we always use s32 for indexing. Apparently deep inside the xla spmd-partitioning there is an implicit assumption on this

feat: add Ops.dynamic_update_slice & Ops.dynamic_slice

---

src/mlir/IR/Pass.jl

Ref: https://github.com/EnzymeAD/Reactant.jl/pull/959#discussion_r2003969079

feat: if passes run fail, dump to a file

---

deps/ReactantExtra/API.cpp

Suggested by @ivanradanov during pair debug session. I still don't know why we can't access this function inside GDB, it works great in Julia though:
```julia-repl
julia> using Reactant, Reactant_jll
julia> mod = @code_hlo optimize = :before_kernel sin.(Reactant.to_rarray(Float32[1.0]));
julia> @ccall libReactantExtra.dump_operation(Reactant.MLIR.IR.Operation(mod).operation.ptr::Ptr{Cvoid}, "this_file.txt"::Ptr{Cchar})::Cvoid
shell> cat this_file.txt
#loc = loc(unknown)
module @reactant_Base.Br... attributes {mhlo.num_partitions = 1 : i64, mhlo.num_replicas = 1 : i64} {
func.func @main(%arg0: tensor<1xf32> {reactant.donated} loc(unknown)) -> tensor<1xf32> {
%0 = stablehlo.sine %arg0 : tensor<1xf32> loc(#loc2)
return %0 : tensor<1xf32> loc(#loc)
} loc(#loc)
} loc(#loc)
#loc1 = …
```

[ReactantExtra] Add debug info to Operation dump

---

deps/ReactantExtra/API.cpp
deps/ReactantExtra/WORKSPACE

This is updating XLA to https://github.com/openxla/xla/commit/821715be3f7ded31723b9b4c0d5de8f0d2a30a6b to solve [upstream issue](https://github.com/openxla/xla/issues/24033) and uses Enzyme-JAX version in https://github.com/EnzymeAD/Enzyme-JAX/pull/511 for testing.

[ReactantExtra] Update XLA and adapt `API.cpp`

---

ext/ReactantOffsetArraysExt.jl

should disambiguate when indexing an `AbstractConcreteArray` with a unit range. See the errors in https://buildkite.com/clima/oceananigans/builds/21674#0195c13d-e9b1-4000-a551-6e09546a77cb
```
MethodError: getindex(::OffsetVector{Float64, ConcreteIFRTArray{Float64, 1, Reactant.Sharding.ShardInfo{Reactant.Sharding.NoSharding, Nothing}}}, ::UnitRange{Int64}) is ambiguous.
  |  
  | Candidates:
  | getindex(A::OffsetVector{T} where T, r::AbstractUnitRange{Int64})
  | @ OffsetArrays /storage5/buildkite-agent/.julia-21674/packages/OffsetArrays/yHW0g/src/OffsetArrays.jl:515
  | getindex(x::OffsetArray{T, N, <:Reactant.AbstractConcreteArray}, args::Vararg{Any, N}) where {T, N}
  | @ ReactantOffsetArraysExt /storage5/buildkite-agent/.julia-21674/packages/Reactant/2J20g/ext/ReactantOffsetArraysExt. …
```

Disambiguate offsetarray `getindex` methods

---

src/mlir/IR/Pass.jl
src/xla/IFRT/LoadedExecutable.jl
src/xla/PJRT/LoadedExecutable.jl

Extending the cases where the MLIR module is written to file in case of failed compilation.  Perhaps not always as useful as we'd like, but better than nothing I guess.

Also dump MLIR module of failed compilation inside IFRT and PJRT

---

src/Distributed.jl

@simone-silvestri was accidentally using PJRT with Distributed. This will be a common error since PJRT is our default runtime. If we detect this combination, we display a loud warning

chore: display loud warning that distributed is being used with PJRT

---

lib/ReactantCore/src/ReactantCore.jl
src/ControlFlow.jl
src/Ops.jl
src/TracedUtils.jl

I should still bump versions but I'm afk for a bit.
```jl
using Reactant
function mysum(x)
s = 0.
a = 10
@trace track_numbers=false for _ in 1:3
a += x
s += x
end
s
end
@code_hlo mysum(ConcreteRNumber(4.))
```
```
ERROR: Types do not match between function arguments and results.
The following arguments should be traced:
a, s
```

nicer error for type mutation in traced loop body

---

src/Compiler.jl
src/Sharding.jl
src/TracedUtils.jl
src/mlir/IR/Context.jl
src/xla/IFRT/Array.jl
src/xla/IFRT/AsyncArray.jl
test/bcast.jl
test/sharding.jl

fix: codegen for resharded input arrays

---

src/Compiler.jl

We don't need to disable the verifier between enzyme and arith raising passes because arith raise is passed in enzyme post passes option. This should help with getting the IR on PM failure.

Run passes on a single PM

---

src/mlir/IR/Pass.jl
test/basic.jl

With `Reactant.MLIR.IR.DUMP_MLIR_ALWAYS[] = true` you can now get a dump of all MLIR modules being compiled, regardless of the success.

Add an option to always dump MLIR module to be compiled

---

src/mlir/IR/Pass.jl
test/basic.jl

In certain cases we were _always_ dumping the modules even with a successful compilation and `DUMP_MLIR_ALWAYS=false`.  Add also a relevant test to catch this mistake.
Ref: https://github.com/EnzymeAD/Reactant.jl/pull/1061#issuecomment-2761297988.

Fix logic for dumping MLIR modules

---

src/Compiler.jl
src/Sharding.jl
test/sharding.jl

As per discussion with @GleasonK on slack, we can't safely run `canonicalize` just after propagation.
* For `xla_default` we are still running propagation outside XLA since we need to extract the sdy shardings (xref #1020). (changed the name because :default wasn't our "default" :P)
* `to_mhlo_shardings` goes all the way and does the full export and drops the sdy attributes (and runs cse, being added upstream to sdy pipeline as well)
* `:none` doesn't run any passes and exists to allow a nicer printing of the generated mlir for end users

fix: shardy passes

---

deps/ReactantExtra/WORKSPACE

This includes https://github.com/openxla/xla/pull/24371 which resolves the issue reported at https://github.com/EnzymeAD/Reactant.jl/pull/1097#issuecomment-2764752677.
I removed `build_bazel_rules_apple` because as far as I understand we already get it from XLA and overriding it here causes more harm than anything else: https://github.com/openxla/xla/issues/24033.  We'll see how this goes in CI, if it doesn't work I'll revert this change.

Update XLA to include bugfix and remove `build_bazel_rules_apple`

---

.github/workflows/CI-localjll.yml

Names weren't sufficiently different enough, making all jobs fail: https://github.com/EnzymeAD/Reactant.jl/actions/workflows/CI-localjll.yml

[CI] Disambiguate names of MLIR artifacts

---

docs/src/tutorials/multihost.md

Existing `echo` commands without `-e` are just wrong.

[docs] Fix syntax to create Project.toml and LocalPreferences.toml

---

Project.toml
test/optimize_comm.jl

Reactant 0.2.69 broke GB-25 and doing any tests there is currently impossible.  Reactant_jll@0.0.139 fixes these issues but also broke a couple of communication optimisation tests here (but only for PJRT apparently), so this PR is temporarily marking them as such until they're fixed.

Use Reactant_jll@0.0.139 and mark broken comms tests as such

---

src/CompileOptions.jl
src/Compiler.jl
src/Reactant.jl
src/Sharding.jl

needs https://github.com/EnzymeAD/Enzyme-JAX/pull/773 + new JLL

feat: pass in new options to optimize-comm

---

src/TracedUtils.jl
test/compile.jl

while readding integration with Reactant.jl in Tenet.jl after a huge refactor, i found out that support for custom trace paths got broken these last months (probably due to the GB sprint).
this PR fixes it and adds a test for it.
@wsmoses maybe we can refactor https://github.com/EnzymeAD/Reactant.jl/blob/main/src/TracedUtils.jl#L493-L504 to allow customization of `stridx`?

fix custom trace paths

---

src/Tracing.jl

idk if there's a better way to check for an undefined box
```
julia> x = Core.Box()
Core.Box(#undef)
julia> x.contents
ERROR: UndefRefError: access to undefined reference
Stacktrace:
[1] getproperty(x::Core.Box, f::Symbol)
@ Base ./Base.jl:37
[2] top-level scope
@ REPL[3]:1
```

Undefined box

---

src/TracedUtils.jl
src/Types.jl
test/tracing.jl

hopefully fixes the sort issue

Fix anytracedarray override

---

deps/build_local.jl

The warning is absolutely spammy.  We also disable the warning in BinaryBuilder,
it's so annoying:
https://github.com/JuliaPackaging/BinaryBuilderBase.jl/blob/99594c5cae8f67b9cdc776418744d88e574d4e05/src/Runner.jl#L449.

Silence unused-command-line-argument warning, not just the error

---

src/CompileOptions.jl
src/Compiler.jl
src/ConcreteRArray.jl
src/xla/IFRT/Array.jl
test/sharding.jl

fix: default to shardy again

---

ext/ReactantKernelAbstractionsExt.jl
src/ConcreteRArray.jl
src/Types.jl
test/layout.jl

I don't know what I was thinking in #1558, but Julia convention is of course
`ArrayType{T}(undef, dims)` and `ArrayType{T}(undef, dims...)`, but *not* `ArrayType(undef, T, dims)`.
Also, the typedef for `ConcreteRArray` was missing `T` and `N` parameters and the typedefs for `ConcreteRNumber` was missing `T`,
This PR fixes that (with deprecation for `ConcreteRArray(undef, T, dims; kwargs...)`) and adds tests.

Fix typedef and undef ctors for ConcreteRArray and ConcreteRNumber

---

deps/ReactantExtra/Project.toml

The job is failing because of the compat bound, but someone should really tests the script still works (I'm really not familiar with the binding generation stuff), since it's a breaking change _some_ breakage should be expected

Update Clang compatibility version to 0.19

---

docs/src/tutorials/automatic-differentiation.md

Updated examples and code snippets in the automatic differentiation tutorial.

docs: should have been marked `@example`

---

Project.toml
docs/src/api/config.md
ext/ReactantZygoteExt.jl
src/Configuration.jl
test/Project.toml
test/integration/zygote.jl
test/runtests.jl

I know @ChrisRackauckas will like this :sweat_smile:

feat: overlay Zygote.gradient and use Enzyme instead

---

Project.toml
src/CompileOptions.jl
src/Compiler.jl
test/ops.jl

feat: enable new auto-batching passes
