- Project.toml
- src/Reactant.jl
- test/basic.jl
Otherwise, `@code_hlo` was actually failing. I added a simple test for `@code_hlo`.
> set global module in compile_to_module

- deps/ReactantExtra/API.cpp
- deps/ReactantExtra/BUILD
- src/Reactant.jl
- src/XLA.jl
- src/mlir/IR/Pass.jl
This prevents exiting when pass fails, and throws a julia exception instead.
> Run pass pipeline from Julia

- .github/workflows/benchmark_pr.yml
- benchmark/benchmarks.jl
trying to split up #86 into smaller parts
> perf: test compile times for neural networks -- VGG16

- ext/ReactantNNlibExt.jl
- test/nn.jl
> NNlib: forward feature group counts to convolution

- .github/workflows/format-check.yml
- .github/workflows/format-pr.yml
the formatter hasn't been running for sometime
> ci(github-actions): update the formatter action

- src/Compiler.jl
- test/basic.jl
@avik-pal the second case seems to hang in compile, but let's get this in first then investigate that separately
> Fix non-used argument

- Project.toml
- ext/ReactantAdaptExt.jl
- ext/ReactantNNlibExt.jl
- ext/ReactantStatisticsExt.jl
- src/ConcreteRArray.jl
- src/Reactant.jl
- src/TracedRArray.jl
- test/basic.jl
- test/runtests.jl
- test/wrapped_arrays.jl
> feat: robust handling of wrapped arrays of reactant arrays

- src/utils.jl
- test/basic.jl
Fixes https://github.com/EnzymeAD/Reactant.jl/issues/151
> Fix vararg

- src/Compiler.jl
- src/TracedRArray.jl
- test/compile.jl
> fix: broadcasted type casting

- src/TracedRArray.jl
- test/basic.jl
> Fix `similar` on `TracedRArray`

- .github/dependabot.yml
- .github/workflows/CI.yml
- .github/workflows/CompatHelper.yml
- .github/workflows/benchmark_pr.yml
- .github/workflows/format-check.yml
- .github/workflows/format-pr.yml
- .github/workflows/regenerate-dialects.yml
* Install Dependabot
* Update some workflows
* Use `julia-actions/cache`
* Colourful julia output
> Improve GitHub Actions settings

- src/Interpreter.jl
Fixes https://github.com/EnzymeAD/Reactant.jl/issues/183
@mofeing probably this is worth just adding these helper functions into EnzymeCore https://github.com/EnzymeAD/Enzyme.jl/blob/main/lib/EnzymeCore/src/EnzymeCore.jl if you want to make a pr and do the requisite bumps
> Add needs primal for forward mode

- src/XLA.jl
- test/basic.jl
See: 
https://github.com/openxla/xla/blob/4bfb5c82a427151d6fe5acad8ebe12cee403036a/xla/xla_data.proto#L103-L106
Should close #172 and #170 (@mofeing can you confirm?).
> fix primitive_type for complex

- .github/workflows/regenerate-mlir-bindings.yml
- src/mlir/libMLIR_h.jl
close #201 
- **fetch lazy artifacts in pre-process step**
- **update libMLIR_h.jl**
> update libMLIR_h bindings and fix bindings update step n°2

- deps/ReactantExtra/API.cpp
> fix complex attr c-api

- deps/ReactantExtra/API.cpp
> Refactor `mlirComplexAttrDoubleGet`, `mlirComplexAttrDoubleGetChecked`

- src/TracedRNumber.jl
- test/complex.jl
> fix abs of complex number

- src/Compiler.jl
see https://buildkite.com/julialang/reactant-dot-jl/builds/1550#01932ba4-dbe6-4466-873b-cd44ce6346b7/320-436
> fix: before_enzyme optimizations

- src/TracedRNumber.jl
- test/basic.jl
> add fill to TracedRNumber

- test/ops.jl
Last numerical tests in #311 other are blocked by #196.
> Ops remaining basic numerical test

- test/basic.jl
the `@testset ConcreteRArray`  was empty.
> add missing @test

- src/utils.jl
Changes needed to make the example run on Julia 1.11
> Kernels: support Julia 1.11

- src/Compiler.jl
See https://discourse.julialang.org/t/error-when-compiling-gather-and-scatter-operation-under-reactant/123930/4?u=avikpal. Useful for users to generate minimal IRs that currently don't have implemented AD.
> feat: add a no_enzyme option

- Project.toml
needs sometime before the changes are propagated
> chore: bump jll

- src/TracedRNumber.jl
Partial but not complete fix for https://github.com/EnzymeAD/Reactant.jl/issues/470
> Fix traced rnumber promotion

- test/basic.jl
> add test for #226

- src/Compiler.jl
- src/Interpreter.jl
- src/Reactant.jl
- src/TracedRArray.jl
- src/TracedUtils.jl
- src/Tracing.jl
- src/stdlibs/Random.jl
fixes #492 
fixes https://github.com/LuxDL/Lux.jl/issues/1186
unfortunately I have no clue how to generate a minimal case for this
> fix: incorrect IR for traced RNGs

- src/Compiler.jl
part of #506 except the rsqrt optimization.
> feat: optimization passes

- src/ConcreteRArray.jl
- test/basic.jl
fixes https://github.com/EnzymeAD/Reactant.jl/issues/542
> feat: add isnan and isfinite dispatches

- src/Overlay.jl
- src/TracedRArray.jl
- src/TracedUtils.jl
- src/Tracing.jl
- test/tracing.jl
Fixes https://github.com/EnzymeAD/Reactant.jl/issues/548
> add int override

- src/TracedRArray.jl
- src/TracedUtils.jl
- test/basic.jl
> fix: define getindexing into sub reshaped array

- deps/ReactantExtra/API.cpp
- deps/ReactantExtra/BUILD
- docs/src/tutorials/profiling.md
> TPU profiler

- deps/ReactantExtra/BUILD
- deps/ReactantExtra/make.jl
> chore: generate shardy c wrappers

- test/autodiff.jl
- test/basic.jl
- test/bcast.jl
- test/nn/nnlib.jl
- test/ops.jl
These changes should make tests much more quiet, thus making it easier to spot other issues when reading the logs.  I split the changes into separate commits to make review easier, in case someone wants to go through them individually.
> Silence various warnings in tests

- deps/Project.toml
- deps/build_local.jl
Remove unused packages from the environment, add more arguments to the script.
> [deps] Some improvements to the `build_local.jl` script

- src/TracedUtils.jl
- test/basic.jl
For small iota, we will expand it in EnzymeJAX. For larger ones it doesn't make too much sense to embed a 10k array into the IR
> fix: don't expand all ranges by default

- ext/ReactantCUDAExt.jl
> [ReactantCUDAExt] Remove extra method

- Project.toml
> Bump to 0.2.30

- src/Ops.jl
- src/TracedRNumber.jl
- test/basic.jl
> Fix implementation of `mod`

- src/Tracing.jl
ref: https://github.com/EnzymeAD/Reactant.jl/issues/769#issuecomment-2667909427
> track number in traced_type for mode == TracedSetPath

- src/Tracing.jl
- test/tracing.jl
> Don't trace VersionNumber

- .github/workflows/CI-localjll.yml
- .github/workflows/CI.yml
- .github/workflows/downgrade.yml
- deps/ReactantExtra/API.cpp
- deps/ReactantExtra/WORKSPACE
- deps/build_local.jl
- deps/clang
- deps/clang++
- deps/gcc
running on API.cpp change doesn't make much sense
> ci: run tests if julia file changes

- src/Compiler.jl
- src/xla/PJRT/LoadedExecutable.jl
- test/basic.jl
> fix: code_xla

- deps/ReactantExtra/WORKSPACE
This for including https://github.com/llvm/llvm-project/pull/128248
> Temporarily use fork of XLA to point to fork of LLVM

- lib/ReactantCore/src/ReactantCore.jl
- test/control_flow.jl
> cf: extract condition to a name

- src/Compiler.jl
> Move executable and device to thunk from expr

- Project.toml
- src/ConcreteRArray.jl
- src/Ops.jl
- src/TracedRArray.jl
- test/basic.jl
Reverts EnzymeAD/Reactant.jl#881.  I believe this broke the GB-25 code.
> Revert "fix: apply init values after reduction"

- src/Ops.jl
- src/TracedRArray.jl
- test/basic.jl
Reverts EnzymeAD/Reactant.jl#896.  Ref: https://github.com/EnzymeAD/Reactant.jl/pull/896#issuecomment-2725429143
> Revert "fix: apply init values after reduce"

- lib/ReactantCore/src/ReactantCore.jl
- test/control_flow.jl
> `@trace if` handle ternary problem

- src/TracedRNumber.jl
- src/TracedUtils.jl
- test/basic.jl
cc @alexandrebouchard
I think the missing piece was just still needing to promote the eltype
> Fix irrational promotion

- src/mlir/IR/Block.jl
- src/mlir/IR/Operation.jl
NFC, I just needed those to massage some MLIR
> Add MLIR function to erase argument and list operands

- src/ConcreteRArray.jl
- test/basic.jl
fixes https://github.com/EnzymeAD/Reactant.jl/issues/943
> fix: flatten before compile

- src/TracedUtils.jl
@wsmoses can you check if this fixes https://github.com/EnzymeAD/Reactant.jl/issues/952
> fix: noop check

- Project.toml
- src/ConcreteRArray.jl
> fix: bcast pjrt

- src/Compiler.jl
- src/ConcreteRArray.jl
- src/xla/IFRT/Array.jl
- test/sharding.jl
turns out if you do weird shit, julia crashes
> fix: bad codegen

- deps/ReactantExtra/API.cpp
- deps/ReactantExtra/WORKSPACE
> [deps] Update to new Enzyme-JAX (which updates to new JAX and Co.)

- docs/src/tutorials/local-build.md
Tip about optimised build with debug info suggested by @ivanradanov.
> [docs] Add more information about local builds

- src/TracedUtils.jl
- test/integration/optimisers.jl
- test/runtests.jl
> fix: empty buffers

- deps/ReactantExtra/API.cpp
- deps/ReactantExtra/BUILD
Absolutely not tested (I'm not even sure `Operation` is the right class here?), but saving the progress before going to sleep.
PS: made in collaboration with @glwagner's best friend.
> [ReactantExtra] Add new function to dump an Operation to file

- deps/build_local.jl
- docs/src/tutorials/local-build.md
* Adapt GCC arguments not just when compiling with CUDA support (that's always needed)
* Fix ID of local build section in the docs
* Add a sample error message for when the Bazel server is killed
> [deps] Some fixes to local build

- deps/build_local.jl
- src/Precompile.jl
- src/Reactant.jl
- src/mlir/MLIR.jl
- src/xla/XLA.jl
Fix #594.  PR best reviewed by [ignoring whitespace changes](https://github.com/EnzymeAD/Reactant.jl/pull/1003/files?w=1)
> Make Reactant loadable when the JLL isn't available

- ext/ReactantCUDAExt.jl
This gets the kernels traced correctly.
> fix: more missing functions

- src/mlir/IR/Pass.jl
At the moment the MLIR module file disappears after the Julia process exits, making this feature not much useful. Ref: https://github.com/EnzymeAD/Reactant.jl/pull/964#discussion_r2008841380.
> Don't cleanup MLIR module written to file when pass fails

- deps/build_local.jl
- src/Ops.jl
might fix the error here https://github.com/PRONTOLab/GB-25/pull/84#issuecomment-2734843574
> Re-enable track_numbers in Ops.while_loop

- ext/ReactantCUDAExt.jl
- src/ConcreteRArray.jl
@simone-silvestri this should fix it
> fix: missing OneTo for ConcreteRNumber

- src/Compiler.jl
- test/buffer_donation.jl
@giordano @avik-pal @glwagner  I believe we accidentally had off by one errors here
> fix arg error

- deps/ReactantExtra/API.cpp
JLL changes for https://github.com/EnzymeAD/Reactant.jl/pull/1076
> fix: remove ifrt::HloSharding handling

- src/Compiler.jl
- src/ConcreteRArray.jl
- test/basic.jl
> fix: codegen to fix aliasing issues

- src/ConcreteRArray.jl
- src/TracedUtils.jl
- test/sharding.jl
> feat: init directly on device

- ext/ReactantCUDAExt.jl
Ref: https://github.com/PRONTOLab/GB-25/pull/154#issuecomment-2778458729
> [ReactantCUDAExt] Don't initialise during precompilation

- deps/ReactantExtra/API.cpp
- deps/ReactantExtra/WORKSPACE
Untested, let's see how it goes.
> [ReactantExtra] Update XLA

- src/xla/IFRT/Array.jl
> fix: better errors

- .JuliaFormatter.toml
- .github/workflows/format-check.yml
- .github/workflows/format-pr.yml
- .github/workflows/regenerate-mlir-bindings.yml
JuliaFormatter@v2 changed the formatting rules, let's stick to the old version for the time being for consistency.
> [CI] Always use JuliaFormatter@v1

- src/Compiler.jl
mostly to get nicer IRs for EnzymeJAX without having to dev reactant
> feat: option to get post sdy propagation IR

- src/Compiler.jl
- src/Sharding.jl
fixes https://github.com/EnzymeAD/Reactant.jl/issues/1346
> docs: document the options to core macros

- src/Compiler.jl
oops previous one was a bad merge
> fix: dicts are mutable

- deps/ReactantExtra/BUILD
> Add missing TableGen files to EnzymeXLA.jl Bazel rule

- .github/workflows/format-pr-bazel.yml
- .github/workflows/format-pr.yml
Ref: https://github.com/EnzymeAD/Reactant.jl/pull/1428#issuecomment-3018068147.
> [CI] Disambiguate titles and branch names for formatting PRs

- Project.toml
- src/Compiler.jl
- src/Tracing.jl
- src/Types.jl
needed to avoid issues like https://github.com/LuxDL/Lux.jl/issues/1358
> fix: expose device and client options in to_rarray

- src/TracedRNumber.jl
Ref https://github.com/CliMA/Oceananigans.jl/pull/4792 and https://github.com/CliMA/Oceananigans.jl/pull/4793#issuecomment-3303516473
> Alias `TracedStepRangeLen` inside `TracedRNumberOverrides` for compatibility

- ext/ReactantPythonCallExt/ReactantPythonCallExt.jl
- ext/ReactantPythonCallExt/overlays.jl
- ext/ReactantPythonCallExt/pycall.jl
- src/Tracing.jl
- test/integration/python.jl
fixes https://github.com/EnzymeAD/Reactant.jl/issues/354
> feat: generalize pycall to support structures

- src/TracedRNumber.jl
- src/utils.jl
- test/basic.jl
> Add support for log2 and log10
